# Generated by Django 4.1.5 on 2023-01-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="School",
        ),
    ]
