# Generated by Django 4.1.5 on 2023-01-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="schools",
        ),
    ]
