# Generated by Django 4.1.5 on 2023-01-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="publish_data",
            field=models.BooleanField(default=False),
        ),
    ]
